title: "My Lab Notebook"
description: "A simple, clean online lab notebook documenting research, teaching, and coding."

# Theme (default Jekyll themes work with GitHub Pages)
theme: jekyll-theme-minimal

# Navigation Links (No Sidebar)
navigation:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research"
  - title: "Teaching"
    url: "/teaching"
  - title: "Protocols"
    url: "/protocols"
  - title: "CV"
    url: "/CV.pdf"
