title: "My Lab Notebook"
description: "A simple, clean online lab notebook documenting research, teaching, and protocols."

theme: jekyll-theme-minimal

navigation:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research"
  - title: "Teaching"
    url: "/teaching"
  - title: "Protocols"
    url: "/protocols"
  - title: "CV"
    url: "/CV.pdf"
