title: "My Lab Notebook"
description: "A Jekyll-based online lab notebook for my research."
theme: jekyll-theme-minimal

# Navigation menu
navigation:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/Research"
  - title: "Teaching"
    url: "/Teaching"
  - title: "Protocols"
    url: "/Protocols"

# Social Media & CV
social:
  GitHub: "https://github.com/shescodingoverhere"
  #BlueSky: "https://twitter.com/your-handle"
  LinkedIn: "https://linkedin.com/in/taylorconway2"
  #GoogleScholar: "https://scholar.google.com/citations?user=your-id"
  #ORCID: "https://orcid.org/your-orcid-id"
  CV: "CV.pdf"
